services:
  certbot-panel:
    image: gitea.tmayt.ir/thaiostream/certbot-panel
    container_name: certbot-panel
    build: .
    ports:
      - "127.0.0.1:4234:8000"
    volumes:
      - certbot-data:/data
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-admin@example.com}
      - CERTBOT_STAGING=${CERTBOT_STAGING:-false}
      - CERTBOT_API_TOKEN=${CERTBOT_API_TOKEN:-}
    restart: unless-stopped

volumes:
  certbot-data:
